### ISSUE TITLE
AttributeError: 'tuple' object has no attribute 'size'

### ISSUE THREAD

**Issue by SSSummer** [jefflai108/Attentive-Filtering-Network#8]

**Comment by SSSummer** [comment]
Traceback (most recent call last):
  File "main.py", line 161, in <module>
    train(args, model, device, train_loader, optimizer, epoch, rnn)
  File "/home/spoof-reply/afn/src/v1_training.py", line 27, in train
    loss = F.binary_cross_entropy(output, target)
  File "/home/python27/lib/python2.7/site-packages/torch/nn/functional.py", line 1592, in binary_cross_entropy
    if not (target.size() == input.size()):
AttributeError: 'tuple' object has no attribute 'size'


the output type is 'turple'? it should be a 'tensor'?
how I fix this problem?
